### ISSUE TITLE
Panic when parsing empty mappings

### ISSUE THREAD

**Issue by dejwk** [goccy/go-yaml#101]
Parsing this doc:

- foo: { }

causes panic in yaml_ast:283 (parseMappingNode), b/c Values slice is empty.

A work-around that I've found is to explicitly check for empty, and use node.GetToken() in such case - but perhaps it would make sense to revise node.GetToken() so that it could be used regardless of whether the mapping is empty. (I am not sure what node.GetToken(), resolving to node.Start, is meant to indicate, but it doesn't point to the first token of the mapping, which I'd expect from the name).

**Comment by goccy** [comment]
@dejwk 
Thanks for the reporting !

But I could not reproduce this issue .
Please report version of `github.com/goccy/go-yaml` and example source ?
