### ISSUE TITLE
The result of marshal and then unmarchal the string may not be the same as the original string.

### ISSUE THREAD

**Issue by k1LoW** [goccy/go-yaml#108]
Hi @goccy !

The result of marshal and then unmarchal the string may not be the same as the original string when last node and it is mult-line string.

Please see following example.

| | gopkg.in/yaml.v2 | goccy/go-yaml v1.5.1 |
| --- | --- | --- |
| playground | [here](https://play.golang.org/p/JjJlY9bF1-q) | [here](https://play.golang.org/p/z8X7nCQghZA) |

**Comment by goccy** [comment]
Thanks for the reporting !
I fixed this problem with #135 and released as `v1.7.12` !

**Comment by k1LoW** [comment]
Thank you !!!!!!! 🎊
