### ISSUE TITLE
goccy doesn't return error when parsing wrong yaml

### ISSUE THREAD

**Issue by jodhi** [goccy/go-yaml#144]
when I tried to parse
```
blabla
- duration: 2
```
goccy/go-yaml lib doesn't return any error.

but when I tried to validate using python3 yaml lib, it returned
```
yaml.scanner.ScannerError: mapping values are not allowed here
  in "a.yml", line 2, column 11
```

http://gopkg.in/yaml.v2 also returning error
thanks, nice lib btw

**Comment by goccy** [comment]
Thank you for reporting !
I'll fix this.

**Comment by goccy** [comment]
It seems to work right.

https://play.golang.org/p/KSoaO_o05Vz
