### ISSUE TITLE
Single quoted string output is not consistent with input

### ISSUE THREAD

**Issue by michaellzc** [goccy/go-yaml#165]
Thanks for the amazing library.

## Description

If the input yaml file contains single-quoted string, they are converted to double-quoted string after marshalling. Is this expected behaviour?

https://play.golang.org/p/JLbpVImLy2K

```go
struct {
	A string `yaml:"username"`
	B string `yaml:"password"`
}
```

Input for unmarshal

```yaml
username: '{{ requiredEnv "USERNAME" }}'
password: '{{ requiredEnv "PASSWORD" }}'
```

Output of marshal

```yaml
username: "{{ requiredEnv \"USERNAME\" }}"
password: "{{ requiredEnv \"PASSWORD\" }}"
```

**Comment by goccy** [comment]
First, go-yaml outputs double quotes by default. 
If once you decode by `yaml.Unmarshal` to string value, 
there is no way to know whether the original string was a single quote or a double quote. 
Therefore, this behavior is intended.

If you want to avoid this behavior, you can do so by using ast.Node API.

**Comment by goccy** [comment]
I think it is good to offer it as an option. For example 
```go
package yaml

type QuoteStyle int

const (
  SingleQuoteStyle QuoteStyle = iota
  DoubleQuoteStyle 
)

func QuoteForEscape(style QuoteStyle) EncodeOption
```

**Comment by mcdee** [comment]
This would be a great addition for me, thanks!

**Comment by goccy** [comment]
Currently, you can use `yaml.UseSingleQuote` option for encoder.
