### ISSUE TITLE
Beautify map of slice output

### ISSUE THREAD

**Issue by bangzek** [goccy/go-yaml#177]
When I encoding this kind of data `map[string][]int{"test": []int{1, 2, 3}}` **go-yaml** and **yaml.v3** gives different output. While both are valid yaml, but **yaml.v3** output is more beautiful.

yaml.v3 output goes like this:
```yaml
test:
    - 1
    - 2
    - 3
```

While this library output:
```yaml
test:
- 1
- 2
- 3
```

While the different is minuscule in that test case, in big heavily nested document it's really ugly.

See https://play.golang.org/p/iGuXlQxJgDD for live comparison.

**Comment by tliron** [comment]
I prefer this library's output. But perhaps there can be an option to choose the style, just like we can choose the indent?

**Comment by tliron** [comment]
How does one set EncodeOptions for Pinter? It seems like Printer defaults to the indented output, but I want to disable it.

**Comment by goccy** [comment]
@tliron 
I didn't intend to change the default behavior between encoder and printer, so I thought the sequence wasn't indented in printer either. If you found indented example, it may be a bug, so please report it !
