### ISSUE TITLE
String array elements node position off by 1

### ISSUE THREAD

**Issue by rspruyt-google** [goccy/go-yaml#185]
Nested string array assignment

e.g.

Strings: ["1",["2",["3",["4",["5",["6",["7",["8",["9"]]]]]]]]]

shows token/token.Position.Column incrementing in units of 4 for each nested node string. This causes an off-by-1 error for each subsequent nesting. I expect Position.Column to increment by 5 each time and point to the same start character of each nested string node element, e.g. "1", "2", ...

This is approximately from the 287c14289f13e9071df2c02d089194b23284178d revision I believe (sorry I didn't capture the revision ID)

Cheers :)

**Comment by rspruyt-google** [comment]
This issue looks to be caused by the incorrect advancement of the column marker. When quotes are processed, the first character is skipped (the quote character), but the "progress" value we increment the position by does not account for skipping this character

**Comment by goccy** [comment]
Thank you for the contribution ! I merged your fixing ! #200
