### ISSUE TITLE
Incorrect line number after using multi-line text

### ISSUE THREAD

**Issue by rspruyt-google** [goccy/go-yaml#186]
When using line breaks "\n" in a YAML file, a standard text editor interprets this as a new line. In the following multi-line string case, "First" will have line position 1. "Second" will have line position 2 according to the parser. However, the latter is actually on line 4th line as most users would see this in a text editor, i.e:

```
1:  - First: "This is several,
2:        lines of code
3:        just a test"
4:  - Second: "another multi-line
5:       example to test"
```
It's possible this is by design, but makes relating tokens back to raw source (which a user can relate to) a chore (i.e. calculating the "real" source line).

**Comment by goccy** [comment]
Maybe, This issue has already been fixed with latest release.
