### ISSUE TITLE
Scanner should return error if a double quote is never closed.

### ISSUE THREAD

**Issue by joshzhang-google** [goccy/go-yaml#187]
```
[
  {
    "step1": {
      "assign": [
        {
          "i": "hello world
        }
      ]
    }
  }
]
```
In above code, hello world begins with a double quote but it's never closed. Scanner never generates a new token nor generates any errors. Scanner should be more strict when enforcing the rule of using quotes, brackets, or braces.

**Comment by goccy** [comment]
Thank you for your reporting. This problem has already been fixed with latest release
