### ISSUE TITLE
question: should ast.* Marshal back to its original form? 

### ISSUE THREAD

**Issue by nickatsegment** [goccy/go-yaml#198]
Seems like the `ast` package is for decoding into. I can't tell from the docs, but it doesn't appear to encode back to YAML well, like `github.com/go-yaml/yaml`'s `Node` type does. For example:

```go
package yamlasttest

import (
	"fmt"

	yaml "github.com/goccy/go-yaml"
	yamlast "github.com/goccy/go-yaml/ast"
)

type S struct {
	S yamlast.StringNode `yaml:"s"`
}

func ExampleStringASTRoundTrip() {
	b, _ := yaml.Marshal(S{
		S: yamlast.StringNode{
			Value: "foo",
		},
	})
	fmt.Printf("%s\n", string(b))
	// Output:
	// s: foo
}
```

```bash
$ go test .
--- FAIL: ExampleStringASTRoundTrip (0.00s)
got:
s:
  basenode: null
  token: null
  value: foo
want:
s: foo
FAIL
FAIL	foo	0.142s
FAIL
```

Is this intended to work? Or am I just assuming functionality here?

**Comment by goccy** [comment]
Thanks for the reporting ! I supported this feature with #203

**Comment by nickatsegment** [comment]
Awesome, thanks @goccy, was expecting to have to implement myself :)
