### ISSUE TITLE
fixing README

### ISSUE THREAD

**Issue by lestrrat** [goccy/go-yaml#2]
READMEの英語を直したいのですが、いくつかわからないところがあるので教えてください

> If omitted anchor name, assigned default rendering name ( strings.ToLower(FieldName) ) as anchor name. If omitted alias name and it's field type is pointer type, assigned anchor name automatically from same pointer address.

よくわからなかったので日本語でどういうことなのか教えてくれるとうれしいです！

**Comment by goccy** [comment]
ありがとうございます！

タグの key として `anchor` と `alias` をサポートしているのですが、
```go
type A struct {
  B *B `yaml:"anchor=a"`
  C *C `yaml:"alias=a"`
}
```
のように `anchor` と `alias` の value として名前を指定すると、その名前でエンコードしてくれるという経路 ( 以下のような出力結果になります )
```yaml
b: &a
 ....
c: *a
```
と、 `anchor` と `alias` に対応する名前を省略すると自動で反映してくれる経路

```go
type A struct {
  B *B `yaml:"anchor"`
  C *B `yaml:"alias"`
}
```
( この状態で、 `A.C` に対して、 `A.B` に設定しているインスタンスと同じものを設定した上でエンコードすると以下のようになります )

```yaml
b: &b
c: *b
```

の二通りがあり、 `alias` の名前を指定しない場合は、そのメンバに設定されているポインタの値から対応する `anchor` を探してきて決定するよということが伝えたかったです！
