### ISSUE TITLE
unmarshal string into time.Duration

### ISSUE THREAD

**Issue by l3uddz** [goccy/go-yaml#201]
Would it be possible to get support for unmarshalling strings into a time.Duration variable (such as `10h` / `10h30m` etc..)

Thanks

**Comment by franchb** [comment]
The same issue:

```go
package main

import (
	"fmt"
	"time"

	"github.com/goccy/go-yaml"
)

type Config struct {
	Batching Batching `yaml:"batching"`
}

type Batching struct {
	Timeout time.Duration `yaml:"timeout"`
	Limit   int           `yaml:"limit"`
}

func main() {
	sample := `
batching:
  timeout: 1s
  limit: 200
`
	var b Config
	if err := yaml.Unmarshal([]byte(sample), &b); err != nil {
		panic(err)
	}
	fmt.Printf("%+v", b)
}
```

Results in:

> panic: cannot unmarshal string into Go struct field Config.Batching of type time.Duration

 https://play.golang.org/p/aH8Pmd4QnMe

**Comment by franchb** [comment]
The latest version parses this case correctly, see https://play.golang.org/p/aH8Pmd4QnMe

@goccy should be this issue closed?

**Comment by goccy** [comment]
@franchb Yes ! Thank you for notification !
