### ISSUE TITLE
Error parsing "is-a-bool: !!bool Yes"

### ISSUE THREAD

**Issue by nicolasboulay** [goccy/go-yaml#214]
When a try to parse

is-a-bool: !!bool Yes

The parser return :

map[is-a-bool:**<nil>**]

but i should have "true".

**Comment by goccy** [comment]
Since this library is implemented based on the 1.2 specification, `yes` and `no` are not intentionally interpreted as boolean. These are present in the 1.1 spec, but are deprecated in 1.2.

**Comment by nicolasboulay** [comment]
So what should be interpreted as true/false ?

Le sam. 13 mars 2021 à 15:18, Masaaki Goshima ***@***.***> a
écrit :

**Comment by goccy** [comment]
@nicolasboulay Are you still need this feature? If so, I’ll consider how to support it.

**Comment by goccy** [comment]
I've supported this feature. Thank you !

**Comment by nicolasboulay** [comment]
thanks !
