### ISSUE TITLE
Incorrect line & column reported

### ISSUE THREAD

**Issue by prymitive** [goccy/go-yaml#219]
When parsing YAML content I see that lines & columns are not always accurate.
Demo here: https://play.golang.org/p/RIVqEbM61KU

Example:
```
- key1: val1
  key2: |
    val2
[...]
```

`val2` ends up with line line `4` and column `-2`. Same for val3.

This value:
```
val7a
/
val7b > 1
```
is reported as line 17, which is more than 1 line off.

**Comment by goccy** [comment]
Thank you for your reports. This problem has already been fixed with latest release.
