### ISSUE TITLE
Parsing AST with comments breaks output

### ISSUE THREAD

**Issue by martin-sucha** [goccy/go-yaml#225]
With version `v1.8.9` the following program:

```go
package main

import (
	"os"

	"github.com/goccy/go-yaml/parser"
)

func main() {
	input := []byte(`
x:
  - a
  #- b
  - c
  #- d
`)
	f, err := parser.ParseBytes(input, parser.ParseComments)
	if err != nil {
		panic(err)
	}
	os.Stdout.Write([]byte(f.String()))
}
```

prints the following unexpected output:

```
x:
  - a
  - - c
#- d
```

I would expect it to print the input unmodified

```
x:
  - a
  #- b
  - c
  #- d

```

**Comment by nakabonne** [comment]
I'm running into the same issue as well.

**Comment by nakabonne** [comment]
Seems like it decodes comments as well as we'd expect.

```go
import "github.com/k0kubun/pp"
func main() {
        yml := `# some comments
        foo: bar`

	p, _ := goyaml.PathString("foo")
	file, _ := parser.ParseBytes(yml, parser.ParseComments)
	pp.Println("file:", file)
}
=>
"file:" &ast.File{
  Name: "",
  Docs: []*ast.DocumentNode{
    &ast.DocumentNode{
      BaseNode: &ast.BaseNode{
        Comment: (*token.Token)(nil),
        read:    0,
      },
      Start: (*token.Token)(nil),
      End:   (*token.Token)(nil),
      Body:  &ast.MappingNode{
        BaseNode: &ast.BaseNode{
          Comment: &token.Token{
            Type:          12,
            CharacterType: 0,
            Indicator:     3,
            Value:         "# some comments\n",
            Origin:        "# some comments\n",
            Position:      &token.Position{
...
```

I feel like all we have to do is to fix String() so that it can encode comments at the proper position.

https://github.com/goccy/go-yaml/blob/b00378283f768eea931dc50c65e5190ad77e0693/ast/ast.go#L1153-L1171

**Comment by goccy** [comment]
I resolved this issue with #233 .

```yaml
x:
  - a
  #- b
  - c
  #- d
```

But the above code converted the following

```yaml
x:
  - a
  #- b
  - c
#- d
```

This is because the library also formats the string as it writes it.

**Comment by nakabonne** [comment]
Thank you for your work! Can't wait to see the next relase.

**Comment by martin-sucha** [comment]
Thank you for fixing this!

> I think the last comment ( #- d ) is not what you intended .
This is because the library also formats the string as it writes it.

The formatted output works for me :+1: .

(Outputting the exact same indentation would be nice feature to have for minimizing diffs when replacing some parts of yaml files, but that definitely does not belong to this issue.)
