### ISSUE TITLE
Support decoding comments at the same line

### ISSUE THREAD

**Issue by nakabonne** [goccy/go-yaml#248]
Hi, since then it encodes comments well. A big thank you goes out to you!

But now I'm running into a problem. It treats comments at the same line as a part of a value. Say for instance, suppose we have:

```go
package main

import (
	"fmt"

	goyaml "github.com/goccy/go-yaml"
	"github.com/goccy/go-yaml/ast"
	"github.com/goccy/go-yaml/parser"
)

const yml = `
foo:
  bar: baz # comment
`

func main() {
	f, _ := parser.ParseBytes([]byte(yml), parser.ParseComments)

	yamlPath, _ := goyaml.PathString("$.foo.bar")

	node, err := yamlPath.FilterFile(f)
	if err != nil {
		panic(err)
	}
	fmt.Printf("node: %s\n\n", node)

	oldNode, _ := yamlPath.FilterFile(f)
	newNode := &ast.StringNode{
		BaseNode: &ast.BaseNode{},
		Token:    oldNode.GetToken(),
		Value:    "new-value",
	}

	yamlPath.ReplaceWithNode(f, newNode)
	fmt.Printf("%s\n", f)
}
```

Expected:

```
$ go run main.go
node: baz

foo:
  bar: new-value # comment
```

But the actual result is:

```
$ go run main.go
node: baz # comment

foo:
  bar: new-value
```

Are you looking to support this kind of comment? It would be nice if you could tell me about it. Thank you.

**Comment by goccy** [comment]
@nakabonne Hi, Thank you for the question.

If comment is added to the key of map (e.g. `a: # comment for key` ), comment will be linked to the node of key.
If you write a comment on the same line as the value of the map like this time (e.g. `a: b # comment for value` ), the comment will be linked to the value.

So you can replace the comment content by calling `ast.(Node).SetComment(*ast.CommentGroupNode) error` for value.

**Comment by nakabonne** [comment]
@goccy Thank you for your response.

Sorry for missing my explanation. What I'm actually stuck with is that the comment at the same line as the value gets deleted after replacing the value. In the above example, it should keep the comment like below even if `$.foo.bar` was replaced.

```yaml
foo:
  bar: new-value # comment
```

**Comment by goccy** [comment]
@nakabonne Is it okay with the following code ?

```go
package main

import (
	"fmt"

	"github.com/goccy/go-yaml"
	"github.com/goccy/go-yaml/ast"
	"github.com/goccy/go-yaml/parser"
)

const yml = `
foo:
  bar: baz # comment
`

func main() {
	f, _ := parser.ParseBytes([]byte(yml), parser.ParseComments)

	yamlPath, _ := yaml.PathString("$.foo.bar")
	oldNode, _ := yamlPath.FilterFile(f)
	newNode := &ast.StringNode{
		BaseNode: &ast.BaseNode{},
		Token:    oldNode.GetToken(),
		Value:    "new-value",
	}
	comment := oldNode.GetComment()
	if comment != nil {
		newNode.SetComment(comment)
	}
	yamlPath.ReplaceWithNode(f, newNode)
	fmt.Printf("%s\n", f)
}
```

**Comment by nakabonne** [comment]
@goccy Ah, I didn't even know those kinds of comments are recognized as a CommentNode. That seems to solve the issue I've been facing, thank you!
