### ISSUE TITLE
value with `!!int64` tag becomes nil without error

### ISSUE THREAD

**Issue by vvakame** [goccy/go-yaml#262]
https://play.golang.org/p/ecNPtvSD1U-

```
variables := make(map[string]interface{})
err := yaml.Unmarshal([]byte("v: !!int64 1"), &variables)
if err != nil {
	panic(err)
}
fmt.Println("%#v", variables)
```

**expected**
become error. because `int64` is not defined on yaml spec. https://yaml.org/spec/1.2.2/#10213-integer

**actual**
ignored.

**Comment by goccy** [comment]
Thank you for your reporting ! Sorry for the late reply, but I'll fix this problem.
