### ISSUE TITLE
How to create MappingValueNode using ast?

### ISSUE THREAD

**Issue by roberto-caylent** [goccy/go-yaml#272]
I'm trying to programatically create a mapping node using the AST API, however I keep getting nil reference errors. What is proper way to use the ast API to programmatically create nodes?

This is the code I'm trying:

`ast.MappingValue(&token2.Token{}, &ast.StringNode{Value: "test"}, &ast.StringNode{Value: "test"})`

and in the struct I hava a field with type `ast.Node`

**Comment by goccy** [comment]
Please use `ast.String(&token.Token{Value: "test"})` to create `*ast.StringNode`
