### ISSUE TITLE
Unmarshal key of `map[int]string` to string, then panic when marshal 

### ISSUE THREAD

**Issue by fy0** [goccy/go-yaml#287]
code to make `go-yaml` panic:

```go
func main() {
	a := map[int64]string{}
	a[123] = "not production ready"
	r1, _ := yaml.Marshal(a)
	fmt.Println(string(r1))
	yaml.Unmarshal(r1, &a)
}
```

panic: reflect.Value.SetMapIndex: value of type string is not assignable to type int64

**Comment by rusq** [comment]
Confirmed with
```go
package main

import (
	"log"
	"strings"

	"github.com/goccy/go-yaml"
)

type Sample struct {
	Test map[int]string
}

var s Sample = Sample{
	Test: map[int]string{
		1: "test",
	},
}

func main() {
	var buf strings.Builder
	enc := yaml.NewEncoder(&buf)
	if err := enc.Encode(s); err != nil {
		log.Fatal(err)
	}
	log.Println(buf.String())

	var decS Sample
	dec := yaml.NewDecoder(strings.NewReader(buf.String()))
	if err := dec.Decode(&decS); err != nil {
		log.Fatal(err)
	}
}
```

**Comment by goccy** [comment]
Thank you for your reporting. We need to validate that the map key is of a valid type before setting the value.

**Comment by goccy** [comment]
This problem has already been fixed with latest release.

**Comment by rusq** [comment]
Thank you for the fix, and for the library - it's my favourite for parsing yaml 🤝

**Comment by goccy** [comment]
@rusq Thank you very much, and also thank you for becoming a sponsor 😄 . It means a lot to me and is very encouraging. If you encounter any issues, please don’t hesitate to report them.
