### ISSUE TITLE
Invalid YAML is successfully parsed

### ISSUE THREAD

**Issue by alsan1998** [goccy/go-yaml#305]
The following snipped is invalid according to https://yaml.org/spec/1.2.2:
`foo: [${should not be allowed}]`

However, it is successfully parsed by goccy (see https://go.dev/play/p/EYtWAcLmWDi).

**Comment by braydonk** [comment]
Further corroboration that this is a bug, `gopkg.in/yaml.v2` correctly fails to parse the invalid block of yaml: https://go.dev/play/p/wFRaLSQ4_xI
