### ISSUE TITLE
Ast unexpected maping value while using comment inside json flow

### ISSUE THREAD

**Issue by Ghibranalj** [goccy/go-yaml#307]
This valid yaml gives out an error when parsed with `parser.ParseBytes()`

```yaml
cursor: {
    # something
    style: beam,
}
```
Error message
```
2022/07/31 17:34:11 [2:5] unexpected mapping key
       1 | cursor: {
    >  2 |     # something
               ^
       3 |     style: beam,
       4 | }
```

Edit:
This online yaml parser parses it correctly [here](https://yaml-online-parser.appspot.com/?yaml=cursor%3A%20%7B%0A%20%20%20%20%23%20something%0A%20%20%20%20style%3A%20beam%2C%0A%7D%0A&type=json).

**Comment by Ghibranalj** [comment]
😭

**Comment by goccy** [comment]
@Ghibranalj  Thank you for your reporting. This problem has already been fixed with latest release.
