### ISSUE TITLE
marshal blank string

### ISSUE THREAD

**Issue by ethfoo** [goccy/go-yaml#309]
`goccy/go-yaml` deal with blank string different from `gopkg.in/yaml.v2`.

CODE

```golang
package main

import (
	"fmt"

	errYaml "github.com/goccy/go-yaml"
	okYaml "gopkg.in/yaml.v2"
)

func main() {
	v := struct {
		Key string
	}{
		Key: " ",
	}
	d1, _ := okYaml.Marshal(v)
	fmt.Printf("%s\n%s\n", "YES", string(d1))

	d2, _ := errYaml.Marshal(v)
	fmt.Printf("%s\n%s\n", "NO", string(d2))

}
```

OUTPUT
```
YES
key: ' '

NO
key:
```
Wondering if this is expected, maybe the `output ' '` is more reasonable.

**Comment by goccy** [comment]
This problem has already been fixed with latest release.
The above example produces `key: " "` by goccy/go-yaml
