### ISSUE TITLE
Empty nodes don't unmarshal properly in structs

### ISSUE THREAD

**Issue by quentinmit** [goccy/go-yaml#313]
go-yaml includes the test case of

```yaml
v:
```

unmarshaling to

```go
map[string]interface{}{"v": nil}
```

but it doesn't include any test cases for unmarshaling into a struct, and in particular the behavior seems different.

```go
type Struct struct {
  V *string `yaml:"v"`
}
```

unmarshals both the empty document and `v:` into `{V: nil}` because of the code at https://github.com/goccy/go-yaml/blame/master/decode.go#L1068 I would expect the empty document to unmarshal to `{V: nil}` but `v:` to unmarshal into `{V: &""}`.

I think this logic should be changed so that the pointer is set to a pointer to the zero value for the type instead of being set to `nil`. The YAML spec in "7.2. Empty Nodes" says:

> Nodes with empty content are interpreted as if they were plain scalars with an empty value.

Without this change, it is impossible to tell whether a field is present or not in a YAML file.

I also tried to work around this by implementing `InterfaceUnmarshaler` but it doesn't seem possible to also invoke the original unmarshaling behavior from `UnmarshalYAML`.

**Comment by quentinmit** [comment]
Reading the YAML spec a bit more, I found this in 10.2.1.1:

> Note that a null is different from an empty string.

I think that implies that the correct behavior is:

- `v:` unmarshals to `{V: &""}` or `map[string]*string{"v": &""}` or `map[string]interface{}{"v": nil}`
- `` unmarshals to `{V: nil}` or `map[string]*string{}`
- `v: null` unmarshals to `{V: nil}` or `map[string]*string{"v": nil}`

since an explicit null is different from an empty node.

**Comment by nieomylnieja** [comment]
it's also contradicts the `encoding/json` behaviour, one workaround for that I found is to use `yaml.UseJSONUnmarshaler()`, but this is not ideal obviously :/ would you consider a contribution to change that @goccy?

**Comment by goccy** [comment]
Thank you for your reporting ! This problem has already been fixed with latest release !
