### ISSUE TITLE
Sentinel errors in yaml render useless stack traces

### ISSUE THREAD

**Issue by kortschak** [goccy/go-yaml#320]
The sentinel error values in the yaml package are constructed with the x/xerrors package which means they capture stack traces when the values are assigned during program initialisation. These stack traces are pointless since they are statically known. They do however contaminate error output since they render due to misalignment with the internal/errors packages printing code.

This can be seen with this program https://go.dev/play/p/KB1hFcLy2Ue which has an intentional error in client code but which renders an error giving no indication where the error occurred, but instead points to the [line on which `yaml.ErrNotFoundNode` is defined](https://github.com/goccy/go-yaml/blob/v1.9.6/error.go#L12).

```
package main

import (
	"fmt"
	"log"

	"github.com/goccy/go-yaml"
	"github.com/goccy/go-yaml/parser"
)

func main() {
	data := `foo: bar`
	f, err := parser.ParseBytes([]byte(data), 0)
	if err != nil {
		log.Fatal(err)
	}

	baz, err := yaml.PathString("$.baz")
	if err != nil {
		log.Fatal(err)
	}

	_, err = baz.FilterFile(f)

	fmt.Println(err)
}
```

Outputs:
```
node not found:
    github.com/goccy/go-yaml.init
        /tmp/gopath3593844022/pkg/mod/github.com/goccy/go-yaml@v1.9.6/error.go:12
```

This is also related to the [ST1005 check](https://staticcheck.io/docs/checks/#ST1005) since it makes it impossible to compose the error string into another single line error without laboriously determining the error that it is.

**Comment by goccy** [comment]
This issue has already been resolved with latest release.
