### ISSUE TITLE
Handling reserved character

### ISSUE THREAD

**Issue by kanata2** [goccy/go-yaml#336]
## Description
I found a behavior that I am curious about. Please let me confirm if this is the intended behavior.

> The "@" (x40, at) and "`" (x60, grave accent) are reserved for future use.
> -- https://yaml.org/spec/1.2.2/

According to the YAML 1.2.2 specification, "@" is a reserved character, but when using goccy/go-yaml, it seemed to be treated as a non-reserved character.
The following is the result of the verification.

## Behavior
I have checked the behavior of both with the following code.

```go:main.go
package main

import "github.com/goccy/go-yaml" // or "gopkg.in/yaml.v3"

type s struct {
	Ss []string
}

var b = []byte(`ss: [@foo, @bar]`)

func main() {
	var s s
	if err := yaml.Unmarshal(b, &s); err != nil {
		panic(err)
	}
	for _, o := range s.Ss {
		println(o)
	}
}

```

### goccy/go-yaml v1.9.2
```console
$ go run main.go
@foo
@bar
```

### gopkg.in/yaml.v3 v3.0.1

```console:output
$ go run main.go
panic: yaml: found character that cannot start any token
...
```

**Comment by shuheiktgw** [comment]
I confirmed both go-yaml/yaml and Online YAML Parser failed parsing the characters "@" and "`" while the latest goccy/go-yaml successfully parsing the characters.

```
import (
	"testing"

	"gopkg.in/yaml.v3"
)

func Test(t *testing.T) {
	tests := []struct {
		desc  string
		input string
	}{
		{
			desc:  "@",
			input: "key: [@val1, @val2]",
		},
		{
			desc:  "`",
			input: "key: [`val1, `val2]",
		},
	}

	for _, tc := range tests {
		t.Run(tc.desc, func(t *testing.T) {
			unmarshalled := map[string]any{}
			if err := yaml.Unmarshal([]byte(tc.input), &unmarshalled); err != nil {
				t.Fatal(err)
			}
		})
	}
}
```

```
=== RUN   Test
=== RUN   Test/@
    test_test.go:29: yaml: found character that cannot start any token
--- FAIL: Test/@ (0.00s)

=== RUN   Test/`
    test_test.go:29: yaml: found character that cannot start any token
--- FAIL: Test/` (0.00s)

--- FAIL: Test (0.00s)

```

**Comment by goccy** [comment]
Thank you for your reporting !

I understand this problem.

> The “@” (x40, at) and “`” (x60, grave accent) are reserved for future use.



https://yaml.org/spec/1.2.2/#10213-integer:~:text=Example%205.9%20Directive%20Indicator
