### ISSUE TITLE
Invalid YAML parses successfully: scalar field mixed into array

### ISSUE THREAD

**Issue by braydonk** [goccy/go-yaml#358]
# Explanation

The following invalid YAML parses successfully:
```yaml
a:
- val1
x: 1
- val2
```
Any variant that has the scalar field at a lower indentation level than the array also parses.

This will also correctly parse into a type like so:
```go
type t struct {
    A []string `yaml:"a"`
}
```
It will fail to parse into this:
```go
type t struct {
    A []string `yaml:"a"`
    X int      `yaml:"x"`
}
```
But will successfully parse into this:
```go
type t struct {
    A []string `yaml:"a"`
    X string   `yaml:"x"`
}
```
# Reproduction 

https://go.dev/play/p/7o1m-XPNl8I

# Theory

I think the root of the problem is that this should fail to parse but doesn't:
```yaml
a: 1
- val1
```
It seems like `a` will be parsed as a string scalar value that includes `\n- val1`, rather than an invalid map key like it should be.
![Putting the above example into yamllint.com](https://user-images.githubusercontent.com/93549768/224131772-e07314cd-a761-447c-9c00-c8ccf32c3f5c.png)

**Comment by goccy** [comment]
Thank you for your reporting ! This problem has already been fixed with latest release.

**Comment by braydonk** [comment]
Thank you for the fix @goccy!
