### ISSUE TITLE
Automatically select quote kind that reduces escaping

### ISSUE THREAD

**Issue by colinking** [goccy/go-yaml#362]
Consider the following field:

```
body: '{ "id": "ev123" }'
```

Since this value includes double quotes, wrapping the string in double quotes would require escaping:

```
body: "{ \"id\": \"ev123\" }"
```

This is significantly harder to read, but unfortunately is the default for `go-yaml`. Ideally, `go-yaml` would detect if a string includes double quotes and fallback to single quotes if it produces a shorter value.

I believe this should be a simple change to `encodeString` [here](https://github.com/goccy/go-yaml/blob/f3319d6c809402b2e4a64de82097d6e7faacfb0c/encode.go#L510) to select which quote kind to use. I'm happy to open a PR for this if this change is likely to be accepted.

**Comment by goccy** [comment]
Please use `yaml.UseSingleQuote` option.
