### ISSUE TITLE
Diff to go-yaml/yaml

### ISSUE THREAD

**Issue by kudla** [goccy/go-yaml#377]
Hi there
There're some questions comparing [goccy/go-yaml](https://github.com/goccy/go-yaml) to [go-yaml/yaml](https://github.com/go-yaml/yaml)

Are these two some evolution branches from the same seed project or are they just completely different standalone projects?

Regarding [goccy/go-yaml](https://github.com/goccy/go-yaml) it self is there currently support (or would it be not a big deal to add such a feature) for
* Ast based Unmarshallers (e.g. `func (c *Type) UnmarshalYaml(node *yaml.ASTNode) error`)
* Custom tags mapping (e.g. `!!CustomType {}` => type CustomType struct{})

And if you guys know the actual status for [go-yaml/yaml](https://github.com/go-yaml/yaml) projects. It looks not that active. What might be the reason. Was it moved to some alternative repo? Is it still maintained for now? Any plans on it?

I'm new to both of them. Still historically there's a dep for [go-yaml/yaml](https://github.com/go-yaml/yaml) one on a project. Is there any comparative table on features (except for the readme advantages). 

Is there any gaps comparing  to [go-yaml/yaml](https://github.com/go-yaml/yaml) or [goccy/go-yaml](https://github.com/goccy/go-yaml) mostly extends the former?
It looks the libs are not just simply interchangeable aren't they? Or is there some migration scenarios?

Thank you.

**Comment by goccy** [comment]
This library is a completely different project from github.com/go-yaml/yaml.
It can do many things that go-yaml/yaml cannot.
