### ISSUE TITLE
comment after `-` causes subsequent queries to fail

### ISSUE THREAD

**Issue by zellyn** [goccy/go-yaml#389]
**Describe the bug**
A comment after a minus sign on its own line introducing an object can cause subsequent queries to fail.

**To Reproduce**

https://go.dev/play/p/vh9dhtCnq-e

**Expected behavior**
A comment after an object minus sign should allow queries to work.

**Version Variables**
 - Go version: 1.21
 - go-yaml's Version: v1.11.1

**Comment by goccy** [comment]
Thank you for your report ! I've fixed this issue with #390

**Comment by goccy** [comment]
I've released https://github.com/goccy/go-yaml/releases/tag/v.1.11.2 for fixing this problem

**Comment by zellyn** [comment]
Oh wow! Thank you, that was fast! 😂
