### ISSUE TITLE
Get positional (Line / Column) information on a node

### ISSUE THREAD

**Issue by pantelis-karamolegkos** [goccy/go-yaml#396]
**Is your feature request related to a problem? Please describe.**

I want to be able to get positional information on a `yaml` node i.e. the line in its text and its column.
I think this is more or less implemented in the official `yaml` golang library. [Line](https://github.com/go-yaml/yaml/blob/v3.0.1/yaml.go#L414) and [Column](https://github.com/go-yaml/yaml/blob/v3.0.1/yaml.go#L415)

**Describe the solution you'd like**

e,g, in the following example

```go
package main

import (
	"fmt"
	"log"
	"strings"

	"github.com/goccy/go-yaml"
)

func main() {
	yml := `
store:
  book:
    - author: john
      price: 10
    - author: ken
      price: 12
	  # comment
  bicycle:
    color: red
    price: 19.95
`
	path, err := yaml.PathString("$.store.book")
	fmt.Printf("%#+v\n", path.String())
	if err != nil {
		log.Fatal(err)
	}
	var authors []interface{}
	if err := path.Read(strings.NewReader(yml), &authors); err != nil {
		log.Fatal(err)
	}
	fmt.Println(authors)
	// [john ken]
}
```

I want to be able say to get something like `path.Line` (2) and `path.Column` (3)

**Describe alternatives you've considered**

**Additional context**

**Comment by nervo** [comment]
@pantelis-karamolegkos use node token for this :)

See: https://go.dev/play/p/OBoPkLaV40w

**Comment by pantelis-karamolegkos** [comment]
Great! Thanks for the suggestion 🎉

**Comment by pantelis-karamolegkos** [comment]
@nervo I just noticed that in the `go` playground example, the column value for the `.store.book` node is `5` while clearly it is in 3rd column; why is that?

**Comment by nervo** [comment]
@pantelis-karamolegkos the `.store.book` path represents the *VALUE* node, it begins where the value begins, aka. right at the first `-`.

**Comment by pantelis-karamolegkos** [comment]
So is there a way for me to get the indentation of the line where `book` actually resides? a.k.a `2`?

**Comment by nervo** [comment]
@pantelis-karamolegkos navigate through token's tree :)
