### ISSUE TITLE
Empty null value gets converted to "null" in token

### ISSUE THREAD

**Issue by mikefarah** [goccy/go-yaml#403]
**Describe the bug**

**To Reproduce**

```yaml
cat:
```

See https://play.golang.com/p/FCsVZ8eQ1J6

**Expected behavior**

The ast token Origin (or value) would have the string value of ""

**Version Variables**
 - go version go1.21.0 linux/amd64
 - go-yaml's Version: v1.11.2

**Additional context**
I'm looking to replace `yq`'s yaml engine with goccy! 

[Updated] Fixed goplay link!

**Comment by goccy** [comment]
This is the correct behavior because, in YAML, the value is considered an omission of null rather than being empty.
