### ISSUE TITLE
Empty null value with line comment causes seg fault

### ISSUE THREAD

**Issue by mikefarah** [goccy/go-yaml#404]
**Describe the bug**

This causes a segfault:

```yaml
cat:
# comment
```

**To Reproduce**

https://go.dev/play/p/MNVPesMed_y

**Expected behavior**
Parses correctly with the comment

**Version Variables**
 - Go version: 1.21 
 - go-yaml's Version: v1.11.2

**Additional context**

**Comment by goccy** [comment]
Thank you for your reporting ! This problem has already been fixed with latest release
