### ISSUE TITLE
Null string gets encoded to null literal

### ISSUE THREAD

**Issue by leononame** [goccy/go-yaml#413]
**Describe the bug**

When encoding the go string `"null"`, it gets encoded into the yaml value `null`, which is the null literal, rather than a yaml string.

**To Reproduce**

```go
package main

import (
	"fmt"

	"github.com/goccy/go-yaml"
)

func main() {
	originalData := map[any]any{"nullString": "null", "nullValue": nil}
	// this prints:
	// map[nullString:null nullValue:<nil>]
	fmt.Printf("%v\n", originalData)

	data, _ := yaml.Marshal(originalData)
	var result map[string]any
	// yaml document:
	// nullString: null
	// nullValue: null

	// but should be:
	// nullString: "null"
	// nullValue: null
	fmt.Println(string(data))

	// after unmarshaling, we get:
	// map[nullString:<nil> nullValue:<nil>]
	yaml.Unmarshal(data, &result)
	fmt.Printf("%v\n", result)
}
```

[Playground Link](https://go.dev/play/p/7tS_-cgx3gu)

**Expected behavior**

It should encode the value as `"null"` rather than `null`. See comment in code snippet above

**Version Variables**
 - Go version: 1.21.5
 - go-yaml's Version: 1.11.2

**Comment by denieryd** [comment]
@leononame hi, i just fixed your issue in this PR - https://github.com/goccy/go-yaml/pull/474

**Comment by goccy** [comment]
This problem has already been fixed with latest release. Thank you @denieryd !
