### ISSUE TITLE
README: document the different license as a feature

### ISSUE THREAD

**Issue by dolmen** [goccy/go-yaml#432]
In the feature list in README, add a line to mention that this project has different licensing terms (in particular doesn't contain Apache 2.0 licensed code)

**Comment by goccy** [comment]
@dolmen I don't understand what you mean, please explain more specifically with reference.

**Comment by goccy** [comment]
@dolmen  I'm closing this Issue because I found that it is incorrect and is not for my library, but for the go-yaml/yaml library.
