### ISSUE TITLE
[Question] Tags support, explicit ast decoding?

### ISSUE THREAD

**Issue by divoxx** [goccy/go-yaml#45]
I've noticed that the `ast` package has a `TagNode`. Are local tags (e.g. `!Foo bar`) supported by the higher level encoder/decoder?

I'm toying with the idea of implementing a YAML templating language, that is context aware, and local tags might be one way to use the YAML language in order to inject a custom type that can be replaced during decoding. 

Another interesting option would be to have a public method in the Decoder that would take a direct reference to an `ast.Node`, allowing the AST to be manipulated previously to being decoded.

Overall, this library is looking great. Good work!

UPDATE: I just realized that explicit AST decoding wouldn't be useful unless the AST can be manipulated, which currently it's not possible. It's an interesting idea but definitely more work than I first though when I wrote the initial question.

**Comment by goccy** [comment]
Hi @divoxx 

There are plans to separate `GlobalTag` and `LocalTag` in future improvements,  
but for now they cannot be distinguished.  
However, you can call `GetToken()` of `ast.TagNode` and 
get the tag string with `token.Value` .  
You can determine whether it is `LocalTag` by looking at its contents.

Also, if you want to use an already manipulated AST,  
can I solve it by preparing an I/F like `(*Decoder).DecodeWithFile(interface{}, *ast.File)` ?

**Comment by divoxx** [comment]
Thanks for the quick answer and the explanation for global vs local tags.

As far as the decode method, I think accepting a `*ast.Node` would be more flexible. For example, I might want to parse the whole document (`*ast.Document`) but I also might want to parse just a subset of the document. That said, taking an `*ast.File` is already helpful. 

That said, I'm not sure if it's currently possible to manipulate the ast? For example, would it be possible to replace value node by another programmatically created one, using the public interface of the ast package?

**Comment by goccy** [comment]
I will add more helpful features at next minor update .

https://github.com/goccy/go-yaml/pull/140

Thanks !
