### ISSUE TITLE
Unmarshal drops lines and does not return error

### ISSUE THREAD

**Issue by jdistler** [goccy/go-yaml#459]
**Describe the bug**
When unmarshalling yaml files with certain kinds of whitespace errors, an error is not returned and all content after the whitespace error is truncated.

**To Reproduce**

https://go.dev/play/p/WgvHk09B-Px

**Expected behavior**

The expected behavior is that at `err := yaml.Unmarshal(originalData, &content);`, we return a non-nil error since we could not parse the entire file.

**Screenshots**

Let's say we have a yaml file with these contents:
```
formatVersion: 1
name: some name
description: |
  some description
continuing the description without proper whitespace
system: some system
source: snowflake
```

This is most definitely invalid yaml -

![Screenshot 2024-07-01 at 1 53 43 PM](https://github.com/goccy/go-yaml/assets/9872693/826704a8-cf2b-4a86-af2e-c91ac914eeec)

![Screenshot 2024-07-01 at 1 53 54 PM](https://github.com/goccy/go-yaml/assets/9872693/401df3f4-59ba-4da8-a8ea-37aaa201d67d)

**Version Variables**
 - Go version: `v1.22.3`
 - go-yaml's Version: `v1.11.2`

**Comment by goccy** [comment]
Thank you for your reports. This problem has already been fixed with latest release.
