### ISSUE TITLE
Run yaml-test-suite on CI

### ISSUE THREAD

**Issue by mx-psi** [goccy/go-yaml#465]
**Is your feature request related to a problem? Please describe.**

Correctness is one of the most important priorities for a parsing library. As evidenced by issues like #460, #455, #407, #406 and #399 among others, this library has quite a few edge cases in which parsing does not work correctly (i.e. according to the YAML specificaiton). While this is [not uncommon](https://matrix.yaml.info/) in YAML implementations, it anecdotically seems like go-yaml has more bugs than other libraries, or at least bugs in some more common cases.

**Describe the solution you'd like**

[yaml/yaml-test-suite](https://github.com/yaml/yaml-test-suite) is a language agnostic test suite widely used for ensuring conformance. Adding this test suite on CI would greatly help in reducing the amount of bugs in this library. All tests that fail today could be skipped and tracked, and existing issues could be tied to failing tests in the test suite.

**Describe alternatives you've considered**

Do nothing?

**Additional context**

I was considering this library for adoption in the opentelemetry-collector repository, this is one of the blockers in my view.

**Comment by goccy** [comment]
Thank you for your reports !
I've already added yaml-test-suite in this repo.
