### ISSUE TITLE
Panic on invalid input

### ISSUE THREAD

**Issue by abrander** [goccy/go-yaml#479]
**Describe the bug**

go-yaml panics on invalid input.

**To Reproduce**

```go
package main

import "github.com/goccy/go-yaml"

func main() {
	target := make(map[string]any)

	yaml.Unmarshal([]byte("0::"), &target)
}
```

Playground link: https://go.dev/play/p/55WKa4zscyX

**Expected behavior**

I expected Unmarshal to return an error and not panic.

**Version Variables**
 - Go version: go1.23.2
 - go-yaml's Version: v1.12.0

**Comment by semihbkgr** [comment]
Hi @abrander, I created a new issue that explains the cause of this panic you encountered.
