### ISSUE TITLE
Comments in a SequenceNode are removed when adding a new element to the SequenceNode

### ISSUE THREAD

**Issue by suzuki-shunsuke** [goccy/go-yaml#502]
**Describe the bug**

I want to append a new element to a SequenceNode keeping comments.
I could append a new element but comments in the SequenceNode were removed.

**To Reproduce**

Please provide a minimum yaml content that can be reproduced.
We are more than happy to use [Go Playground](https://go.dev/play)

https://go.dev/play/p/27cMKnuAVKM

**Expected behavior**

Original YAML:

```yaml
packages:
  - foo
  # hello
  - bar
```

I want to append a new element to the packages keeping the comment `# hello`.

```yaml
packages:
  - foo
  # hello
  - bar
  - zoo
```

But actually the comment was removed.

```yaml
packages:
  - foo
  - bar
  - zoo
```

**Screenshots**

**Version Variables**
 - Go version: [e.g. 1.21 ] 1.23.2
 - go-yaml's Version: [e.g. v1.11.1 ] 1.13.3

**Additional context**

**Comment by goccy** [comment]
@suzuki-shunsuke This is due to the implementation for comment output. Comments are linked to the `ValueHeadComments` field of the `SequenceNode` and need to stay synchronized with the elements in Values.
Therefore, when directly adding nodes to Values, you must also add corresponding elements to `ValueHeadComments`.

https://go.dev/play/p/A8Sc3s85c0P

**Comment by suzuki-shunsuke** [comment]
Thank you for your answer!
I confirmed your answer works well.
But I noticed that the type of `file.Docs[0].Body` was changed from `*ast.MappingValueNode` to `*ast.MappingNode`.
Is this breaking change?
I''ll check which version the type was changed from.

https://go.dev/play/p/27cMKnuAVKM

1. go-yaml v1.13.3

go.mod

```
module foo

go 1.23.3

require github.com/goccy/go-yaml v1.13.3

require (
	github.com/fatih/color v1.18.0 // indirect
	github.com/mattn/go-colorable v0.1.13 // indirect
	github.com/mattn/go-isatty v0.0.20 // indirect
	golang.org/x/sys v0.26.0 // indirect
)
```

```console
$ go run main.go
packages:
  - foo
  - bar
  - zoo
```

2. go-yaml v1.15.6

go.mod

```
module foo

go 1.23.3

require github.com/goccy/go-yaml v1.15.6
```

```console
$ go run before.go 
panic: interface conversion: ast.Node is *ast.MappingNode, not *ast.MappingValueNode

goroutine 1 [running]:
main.core()
	/Users/s-suzuki/test/go/goccy/go-yaml/before.go:33 +0x210
main.main()
	/Users/s-suzuki/test/go/goccy/go-yaml/before.go:13 +0x1c
exit status 2
```

**Comment by suzuki-shunsuke** [comment]
I've confirmed the type was changed at v1.15.0.

v1.14.3

```
module foo

go 1.23.3

require github.com/goccy/go-yaml v1.14.3
```

```console
$ go run before.go
packages:
  - foo
  - bar
  - zoo
```

v1.15.0

```
module foo

go 1.23.3

require github.com/goccy/go-yaml v1.15.0
```

```console
$ go run before.go
panic: interface conversion: ast.Node is *ast.MappingNode, not *ast.MappingValueNode

goroutine 1 [running]:
main.core()
	/Users/s-suzuki/test/go/goccy/go-yaml/before.go:33 +0x210
main.main()
	/Users/s-suzuki/test/go/goccy/go-yaml/before.go:13 +0x1c
exit status 2
```

**Comment by goccy** [comment]
That's correct. It always became a `MappingNode`.

**Comment by suzuki-shunsuke** [comment]
I see. Thank you!
I close this issue.
Please keep up the great work!
