### ISSUE TITLE
Inconsistent behavior when the key type doesn't match when unmarshaling

### ISSUE THREAD

**Issue by shuheiktgw** [goccy/go-yaml#508]
**Describe the bug**
While implementing https://github.com/goccy/go-yaml/issues/466, I’ve observed inconsistent behavior with the unmarshaling function. When the key is an integer and the value is empty, unmarshaling it into a map with string keys succeeds. However, if the key is an integer and the value is set, the same operation fails with an error.

**To Reproduce**

In the test code below, the first and second test cases passed, but the third case failed with an error saying `a string was used where a mapping is expected`. I believe the correct behavior is that first case fails like the third case.

```
import (
	"fmt"
	"testing"

	"github.com/goccy/go-yaml"
)

func Test(t *testing.T) {
	tests := []struct {
		desc  string
		input string
	}{
		{
			desc:  "int key without value",
			input: "1:",
		},
		{
			desc:  "string key without value",
			input: "key:",
		},
		{
			desc:  "int key with value",
			input: "1:val",
		},
	}

	for _, tc := range tests {
		t.Run(tc.desc, func(t *testing.T) {
			unmarshalled := map[string]any{}
			if err := yaml.Unmarshal([]byte(tc.input), &unmarshalled); err != nil {
				t.Fatal(err)
			}
			fmt.Println(tc.desc)
			fmt.Printf("map size: %d\n", len(unmarshalled))
			fmt.Println("map entries:")
			for k, v := range unmarshalled {
				fmt.Printf("key: %s, value: %v\n", k, v)
			}
		})
	}
}
```

```
=== RUN   Test
=== RUN   Test/int_key_without_value
int key without value
map size: 1
map entries:
key: A, value: <nil>
--- PASS: Test/int_key_without_value (0.00s)
=== RUN   Test/string_key_without_value
string key without value
map size: 1
map entries:
key: key, value: <nil>
--- PASS: Test/string_key_without_value (0.00s)
=== RUN   Test/int_key_with_value
    test_test.go:33: [1:1] string was used where mapping is expected
        >  1 | 1:val
               ^
        
--- FAIL: Test/int_key_with_value (0.00s)

--- FAIL: Test (0.00s)

FAIL
```

**Version Variables**
 - Go version: 1.23.2
 - go-yaml's Version: v1.13.5

**Additional context**
https://github.com/goccy/go-yaml/issues/331 seems to be related to this issue even though some of the problem have been already fixed.

**Comment by goccy** [comment]
`1:val` is a string value ( `"1:val"` ), it's not map value, so this behavior is correct.
But we need to consider to convert `1` value to string value
