### ISSUE TITLE
Comments split files into documents

### ISSUE THREAD

**Issue by PaulSonOfLars** [goccy/go-yaml#51]
When using `parse.ParseFile()`, I find that my single-document yaml file will get split into multiple documents every time I hit a comment; is this intentional?

example YAML to reproduce this:
```yaml
key1: data
key2: data
# Comment
key3: data
```

Another question I have is regarding the comment parsing; the only `ast.Mode` available is ParseComments (which is fine), however... calling `.String()` on `*ast.File`, or `*ast.Document`, does not display comments.

**Comment by kcmannem** [comment]
I just ran into this as well and took a while to debug. I thought I was going crazy.

**Comment by goccy** [comment]
Oh... Sorry, I will fix this issue.

**Comment by goccy** [comment]
@PaulSonOfLars @kcmannem 
I fixed this issue with #103 and released as `v1.4.5` .

Thanks

**Comment by kcmannem** [comment]
@goccy Appreciate this! Thank you.
