### ISSUE TITLE
FormatError unexpectedly includes source

### ISSUE THREAD

**Issue by markdumay** [goccy/go-yaml#517]
**Describe the bug**
The function [FormatError](https://github.com/goccy/go-yaml/blob/v1.13.7/yaml.go#L214) includes an argument `inclSource`. When set to true, the error message should contain snippets of the YAML source that was used. However, setting `inclSource` to false still displays the YAML source snippet.

**To Reproduce**
https://go.dev/play/p/0rFUNptzt1t

**Expected behavior**
When `inclSource` is set to false, `FormatError()` should not include the YAML source snippet in the rendered error message.

**Screenshots**
N/A

**Version Variables**
 - Go version: v1.23
 - go-yaml's Version: v1.13.7

**Additional context**
N/A

**Comment by goccy** [comment]
Thank you for your reports ! I've fixed this problem with v1.14.1 !

**Comment by markdumay** [comment]
Thanks @goccy!
