### ISSUE TITLE
\t in quoted string is parsed to "\t"

### ISSUE THREAD

**Issue by wxdao** [goccy/go-yaml#537]
**Describe the bug**

\t in quoted string is parsed to "\t".

**To Reproduce**

https://play.golang.com/p/ZDB67ghxTk-

```
package main

import (
	"encoding/json"

	"github.com/goccy/go-yaml"
)

func main() {
	js := `"Hello\tWorld"`

	{
		var s string
		yaml.Unmarshal([]byte(js), &s)

		println(s)
	}

	{
		var s string
		json.Unmarshal([]byte(js), &s)

		println(s)
	}
}
```

got:

```
Hello\tWorld
Hello	World
```

**Expected behavior**

```
Hello	World
Hello	World
```

**Version Variables**
 - go-yaml's Version: latest

**Comment by goccy** [comment]
@wxdao  Thank you for your reports !! I've fixed this problem with v1.14.2 !
