### ISSUE TITLE
Unsupported escaped characters \a and \/

### ISSUE THREAD

**Issue by apstndb** [goccy/go-yaml#561]
**Describe the bug**

Escaped characters `\a` and `\/` are not supported.
They are documented here.
https://yaml.org/spec/1.2.2/#57-escaped-characters

> Escaped ASCII bell (x07) character.
> 
> ```[43] ns-esc-bell ::= 'a'```
> 
> scaped ASCII slash (x2F), for [JSON compatibility](https://yaml.org/spec/1.2.2/#yaml-directives).
> 
> ```[53] ns-esc-slash ::= '/'```

**To Reproduce**
https://go.dev/play/p/LyP5F1vUARi

**Expected behavior**
All escaped characters are supported.

**Version Variables**
 - Go version: Go 1.23.2
 - go-yaml's Version: v1.15.4

**Additional context**

I've found this incompatibility in testcases of [`bufbuild/protoyaml-go`](https://github.com/bufbuild/protoyaml-go).
This appears to be explicitly tested, since string of Protocol Buffers also supports `\a`.

https://protobuf.dev/reference/protobuf/edition-2023-spec/#string_literals

> ```
> charEscape = '\' ( "a" | "b" | "f" | "n" | "r" | "t" | "v" | '\' | "'" | '"' )
> ```

**Comment by goccy** [comment]
Thank you for your report ! I've fixed this problem with #562
