### ISSUE TITLE
Maintain Empty Line information in AST

### ISSUE THREAD

**Issue by braydonk** [goccy/go-yaml#566]
**Is your feature request related to a problem? Please describe.**
Since YAML parsers are not required to maintain empty line information, no available YAML library is capable of parsing YAML and reproducing the exact same line break information. 

To explain what I mean, the following YAML in:
```yaml
a: 1

b: 2
```
Coming back out would look like this:
```yaml
a: 1
b: 2
```
This is because the parser will toss away the empty lines, since they are not vital syntax information and are only for readability.

**Describe the solution you'd like**
A solution similar to the `WithComments` option would be really great to have this.

**Describe alternatives you've considered**
In my tool [yamlfmt](https://github.com/google/yamlfmt) I have a hack that works 75% of the time, which is to add a magic comment line to every empty line break before sending it into the parser, and replacing that magic line with linebreaks on the way out. https://github.com/google/yamlfmt/blob/1bfe5e4a8cf49bf0cdc3e77aa2ffbfb46a1bc812/internal/hotfix/retain_line_break.go#L29

This works a decent amount of the time, but causes strange errors in weird edge cases, and YAML is essentially a language of weird edge cases. :smiling_face_with_tear: 

**Additional context**
I have tried to implement this myself in [my fork of yaml.v3](https://github.com/braydonk/yaml) but it has proven to be infeasible. I also tried in this library but had no luck. That's why I decided to make an issue to see if anyone has ideas for whether this is feasible. If it is, I'm willing to do any implementation work.

**Comment by goccy** [comment]
@braydonk  This PR seems to be related. The functionality to preserve empty lines is already implemented, but did it not work as expected?

https://github.com/goccy/go-yaml/pull/412

**Comment by braydonk** [comment]
Thanks @goccy I didn't notice that! I followed the lineage of that PR to see how they were using the library, and when I do the same thing the line breaks are maintained as expected. Thank you!
