### ISSUE TITLE
ast.Merge() removes comments in a SequenceNode

### ISSUE THREAD

**Issue by suzuki-shunsuke** [goccy/go-yaml#569]
**Describe the bug**

When we merge two SequenceNodes by ast.Merge, comments are removed.

**To Reproduce**

Please provide a minimum yaml content that can be reproduced.
We are more than happy to use [Go Playground](https://go.dev/play)

https://go.dev/play/p/xTKF9ON8bUd

**Expected behavior**

ast.Merge keeps comments.

```
- foo
# hello
- bar
- zoo
- baz
```

**Screenshots**

**Version Variables**
 - Go version: [e.g. 1.21 ] 1.23
 - go-yaml's Version: [e.g. v1.11.1 ] 1.15.6

**Additional context**

- https://github.com/goccy/go-yaml/issues/502#issuecomment-2515981600

I reported the similar issue before.
ast.Merge doesn't update `ValueHeadComments`.

https://github.com/goccy/go-yaml/blob/5d22eed00009e4cd6cf5eaf9848f77c0477d23a8/ast/ast.go#L1473-L1478

✅ I'll create a pull request to resolve this issue. https://github.com/goccy/go-yaml/pull/570

**Comment by suzuki-shunsuke** [comment]
- https://github.com/goccy/go-yaml/pull/570

**Comment by goccy** [comment]
This problem has already been fixed with v1.15.7.
