### ISSUE TITLE
Mandatory escaping for values

### ISSUE THREAD

**Issue by rez1dent3** [goccy/go-yaml#571]
Hello

**Describe the bug**
Unexpectedly the library started checking escaping inside yaml values.
I have a mock service that can be configured via your package and my contract broke. There are projects that also write regular expressions in their mocks' stubs and they broke. Example: 
https://github.com/bavix/gripmock/blob/3e4d95e7f2e566b5cbdb49b4c2cc222cd8ec82b5/example/simple/stub/uint64_int64.yml#L17-L24

**To Reproduce**

https://go.dev/play/p/4addaO985bw

**Expected behavior**
Escaping is expected to be unnecessary. It broke not so long ago. Everything worked fine on v1.15.3. I learned about the problem through dependabot, which brought a PR to update the package.
https://github.com/bavix/gripmock/actions/runs/12131010265/job/33822397280?pr=448
https://github.com/bavix/gripmock/pull/448

**Version Variables**
 - Go version: [ 1.23 ]
 - go-yaml's Version: [ v1.15.4, v1.15.5, v1.15.6 ]

**Comment by rez1dent3** [comment]
https://github.com/bavix/gripmock/pull/447

**Comment by goccy** [comment]
@rez1dent3 This is the correct behavior. The previous behavior was incorrect.

**Comment by rez1dent3** [comment]
Okay 👌
