### ISSUE TITLE
bug: MarshalYAML does not get called

### ISSUE THREAD

**Issue by gabyx** [goccy/go-yaml#573]
**Describe the bug**

A custom type `Custom` which implements `UnmarshalYAML` and `MarshalYAML` does not work as expected.
The `MarshalYAML` does not get called.

**To Reproduce**

```go
package main

import (
	"testing"

	"github.com/goccy/go-yaml"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

type Custom struct {
	Check bool
}

var unmarshalCalled = false
var marshalCalled = false

func (b *Custom) UnmarshalYAML(unmarshal func(any) error) error {
	unmarshalCalled = true
	return unmarshal(&b.Check)
}

func (b *Custom) MarshalYAML() (any, error) {
	marshalCalled = true
	return b, nil
}

type A struct {
	Value Custom `yaml:"value"`
}

func TestGoccyYAML(t *testing.T) {
	a := A{Value: Custom{true}}
	s, e := yaml.Marshal(&a)
	t.Logf("Yaml:\n---\n%s\n---", string(s))

	assert.True(t, marshalCalled, "mashall not called")
	require.NoError(t, e)

	b := A{}
	e = yaml.Unmarshal(s, &b)
	assert.True(t, unmarshalCalled, "unmarshal not called")
	require.NoError(t, e)

	assert.Equal(t, a, b)
}
```

https://go.dev/play/p/wW8S8TNC0mb

**Expected behavior**

The `MarshalYAML` should get called.
Also I dont see any testcase which tests the `InterfaceMarshaller`?

**Version Variables**
 - Go version: 1.23
 - go-yaml's Version: 1.15.6

**Comment by goccy** [comment]
Basically, you should use same type receiver type and field type. This example is specified `Custom` type at field, but receiver type is `*Custom` type
