### ISSUE TITLE
[Question] Wrong indentation?

### ISSUE THREAD

**Issue by pauldthomson** [goccy/go-yaml#58]
Given the following:
```
func main() {
	mystruct := Struct{
		Inner{
			map[string]string{"Woo": "Hoo"},
		},
	}
	yaml, err := yaml.Marshal(mystruct)

	if err != nil {
		fmt.Printf("Oh no! %v", err)
	}

	fmt.Printf("We have:\n%s\n", yaml)
}

type Struct struct {
	Inner Inner
}

type Inner struct {
	Map map[string]string
}
```
I'd expect the output to look like:
```
We have:
inner:
  map:
    Woo: Hoo
```
but instead I get:
```
We have:
inner:
  map:
  Woo: Hoo
```
Where attributes of `map` are not indented. Am I doing something wrong? If I use https://github.com/go-yaml/yaml the output is as expected

**Comment by goccy** [comment]
@pauldthomson 

Thanks for the reporting !
I fixed with #59 and released as v1.1.4 .
