### ISSUE TITLE
Large hex strings are unquoted when marshalled

### ISSUE THREAD

**Issue by mcdee** [goccy/go-yaml#586]
**Describe the bug**

Large hex strings are being encoded without quotes, and small hex strings are being encoded with quotes.

**To Reproduce**

https://go.dev/play/p/U1vXmvyBhLt

**Expected behavior**

Hex strings should remain quoted regardless of length.

**Version Variables**
 - Go version: 1.23.2
 - go-yaml's Version: 1.15.8

**Comment by goccy** [comment]
@mcdee Thank you for your reports ! We've fixed this problem with latest release.
