### ISSUE TITLE
yaml parser no longer errors on invalid yaml

### ISSUE THREAD

**Issue by cpuguy83** [goccy/go-yaml#588]
**Describe the bug**

Given some invalid yaml:
```yaml
foo { totallyInvalid }
```

I also tried this and it did not error:

```yaml
- foo
- bar
  - baz
```

The parser should, and used to, error out (with `parser.ParseBytes`)
We updated from 1.12.0 to 1.15.8 and noticed this behavior change.

There are some other, more complicated, things that unexpectedly did not error out before as well that continue to not error

In this example , the indentation is not correct for the string.
This ends up just dropping the data and incorrectly, but without error, parsing the rest of the document.

```yaml
foo: |
  asdf
```

**Comment by goccy** [comment]
@cpuguy83  These cases are all **VALID** yaml, so this behavior is correct.
