### ISSUE TITLE
Yaml Path panics with invalid path

### ISSUE THREAD

**Issue by gkampitakis** [goccy/go-yaml#595]
**Describe the bug**

Hey, thanks a lot for creating and maintaining this library. I have started exploring this library as part of extending a snapshot testing library that I have https://github.com/gkampitakis/go-snaps and I want to support YAML snapshots. I was looking into `yaml.PathString` and when I pass a path with starting with a dot it panics.

Also apart from the README.md I can't find any examples or documentation for the valid yaml path syntax, maybe I missed it.  

**To Reproduce**

```go
package main

import (
	"github.com/goccy/go-yaml"
)

func main() {
	yaml.PathString(".address")
}


/**
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x20 pc=0x104765254]

goroutine 1 [running]:
github.com/goccy/go-yaml.(*PathBuilder).child(...)
*/

```

Please provide a minimum yaml content that can be reproduced.
We are more than happy to use [Go Playground](https://go.dev/play)

**Expected behavior**

I would expect an error if this is invalid path. 

**Version Variables**
 - Go version: 1.23.2
 - go-yaml's Version:  v1.15.10

**Additional context**

**Comment by goccy** [comment]
Thank you for your reports !
You need to specify `$.` at first, but I've fixed panic in this case with latest release.
