### ISSUE TITLE
`value is not allowed in this context` error on merge with additional property

### ISSUE THREAD

**Issue by dastrobu** [goccy/go-yaml#596]
**Describe the bug**
There is `value is not allowed in this context` error on merge with an additional property instead of unmarshalling the yaml correctly. 

**To Reproduce**

Unmarshal:

```yaml
foo: &bar
  biz: buz
mergeMe:
  !!merge <<: *bar
  foo: bar
```

produces: 

```
Unmarshall() error = [6:3] value is not allowed in this context
           3 |   biz: buz
           4 | mergeMe:
           5 |   !!merge <<: *bar
        >  6 |   foo: bar
                 ^
```

**Expected behavior**

The equivalent of the following JSON should be the result: 

```json
{
  "mergeMe": {
    "foo": "bar", 
    "biz": "buz"
  }, 
  "foo": {
    "biz": "buz"
  }
}
```

Verify with https://yaml-online-parser.appspot.com

**Screenshots**

**Version Variables**
 - Go version: 1.23
 - go-yaml's Version: v1.15.10

**Additional context**

`gopkg.in/yaml.v3` can parse the example correctly.

**Comment by goccy** [comment]
Thank you for your reports !
This problem was caused by `!!merge` tag. I've fixed this problem with latest release.
