### ISSUE TITLE
Windows line endings not supported

### ISSUE THREAD

**Issue by TobsCore** [goccy/go-yaml#65]
When yaml files are read, that have windows line endings (CRLF), the application fails, as it does not recognize the YAML file correctly.

I created a small example repository that showcases the issue. You can check it out at [TobsCore/yaml-crlf-error](https://github.com/TobsCore/yaml-crlf-error).

The error that occurs is as follows:
```
panic: Cannot parse yaml [2:1] unexpected key name
       1 | ---
    >  2 | name: TobsCore
       3 | age: 40
          ^

goroutine 1 [running]:
main.main()
	/tmp/yaml-crlf-error/main.go:26 +0x240
exit status 2
```

**Comment by goccy** [comment]
@TobsCore 

Thanks for the reporting !
I fixed with #66  and released as [v1.1.6](https://github.com/goccy/go-yaml/releases/tag/v1.1.6)
