### ISSUE TITLE
Decoder silently replaces values for duplicate keys in map nodes

### ISSUE THREAD

**Issue by dawidk-g** [goccy/go-yaml#79]
There should be an option to make it fail when it encounters a duplicate key. (BTW, I believe this is what UnmarshallStrict() is doing in go-yaml). Perhaps a new DecodeOption?

**Comment by goccy** [comment]
Well !!
I think it's better to add an option like `DisallowDuplicateKey`

**Comment by goccy** [comment]
This issue was fixed with #112 
( It released as v1.6.1 )
