### ISSUE TITLE
Distinguish between empty slice and nil slice OR Encode both empty and nil slices into `[]`

### ISSUE THREAD

**Issue by k1LoW** [goccy/go-yaml#80]
Hi @goccy !!

Thank you for your GREAT library !! 

I want to encode "empty slices" and "nil slices" as follows

- **Plan 1:** Distinguish between empty slice and nil slice **like encoding/json**
- **Plan 2:** Encode both empty and nil slices into `[]` **like go-yaml/yaml**

| | go-yaml/yaml | encoding/json | goccy/go-yaml.Flow(false) ( default ) | goccy/go-yaml.Flow(true) | goccy/go-yaml.Flow(Plan 1) | goccy/go-yaml.Flow(Plan 2) |
| --- | --- | --- | --- | --- | --- | --- |
| empty slice ( `[]string{}` ) | `a: []` | `{"a": []}` | `a: ` | `a: []` | `a: []` | `a: []` |
| nil slice ( `[]string(nil)` ) | `a: []` | `{"a": null}` | `a: ` | `a: []` | `a: ` | `a: []` |
| play.golang.org OR **commit** | [here](https://play.golang.org/p/Qkq3L1bNFx1) | [here](https://play.golang.org/p/jXbUz8BvF0Z) | [here](https://play.golang.org/p/l3MSm9E_llZ) | [here](https://play.golang.org/p/IhGJGRypHM1) | **[commit](https://github.com/k1LoW/go-yaml/commit/a8dfd3908106f5328e0fec82a1b1f86364edcc60)** | **[commit](https://github.com/k1LoW/go-yaml/commit/7286d8180807e26d21cd5c32a7235df6d2fd3cf0)** |

What do you think about handling this empty slice and nil slice ?

**Comment by goccy** [comment]
Thank you for the detailed report ! **Plan 2** looks good !!

**Comment by k1LoW** [comment]
@goccy Thank for your quick reply !!

I have submitted a PR ( https://github.com/goccy/go-yaml/pull/81 ).

**Comment by goccy** [comment]
I merged that PR ! Thanks !

**Comment by k1LoW** [comment]
Yah! Thank you !!
