### ISSUE TITLE
[help] how create custom Interface Marshaler/Unmarshaler for math/big.Rat and math/big.Int

### ISSUE THREAD

**Issue by danieagle** [goccy/go-yaml#96]
Hi!

I need guidance of how use big.Rat(ionale) and big.Int in YAML. all sugestions and hints are wellcome!
I ready the docs and especification, besides this I am a complete newbe in YAML.

Thanks a Lot!

[]'s Danieagle

**Comment by goccy** [comment]
It supports up to the range of `int64` or `uint64` .
So if you exceed it, should implement `MarshalYAML` / `UnmarshalYAML` to handle it .

```go
import "math/big"

type BigInt big.Int

func (i BigInt) MarshalYAML() ([]byte, error) {
	return []byte(i.String()), nil
}

func (i *BigInt) UnmarshalYAML(b []byte) error {
	var v string
	if err := yaml.Unmarshal(b, &v); err != nil {
		return err
	}
	i.SetString(v)
	return nil
}
```

**Comment by danielwhite** [comment]
FWIW, these types implement `encoding.TextUnmarshaler` and `encoding.TextMarshaler` interfaces, so they should work out of the box.

See: https://play.golang.org/p/t3D8AlQI6ch

```go
package main

import (
	"fmt"
	"math/big"

	"github.com/goccy/go-yaml"
)

func main() {
	var doc struct {
		X *big.Rat `yaml:"x"`
	}
	err := yaml.Unmarshal([]byte("x: 5/4\n"), &doc)
	fmt.Println(err)
	fmt.Printf("%+v\n", doc)

	b, err := yaml.Marshal(doc)
	fmt.Println(err)
	fmt.Println(string(b))
}
```

I've noticed that `*big.Int` currently gets the following error:

> panic: interface conversion: interface {} is uint64, not string

https://github.com/goccy/go-yaml/pull/141 was intended to ensure that anchors work correctly for types implementing `encoding.TextMarshaler`, but also appears to allow `*big.Int` to be used directly.
